### ISSUE TITLE
permit top-level await

### ISSUE THREAD

**Issue by gr2m** [orta/octokit-playground#4]
The current configuration does not permit a top level await

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/39992/114634372-3ccc5f00-9c77-11eb-8ad6-2e4be7e5a208.png">

I've look through the docs and googled, but I couldn't figure out if there is a setting to explicitly set the editor into a "module" mode which permits top level await. Do you know if there is such a thing?

**Comment by gr2m** [comment]
it would be nice to disable the error for async iterators, too. I want to take the code and eval it in an async function, so these errors do not apply

<img width="727" alt="image" src="https://user-images.githubusercontent.com/39992/114636234-612a3a80-9c7b-11eb-986d-9ef71567a488.png">

**Comment by orta** [comment]
I don't think there's a compiler setting for forcing a module, it probably won't come in until there's real node ESM support in the compiler

Monaco also doesn't really let you hide code, so you can't hide it in a wrapped async func. Try setting the compiler options  to have ESNext (99) as the target and you might be able to get away with some of this

**Comment by gr2m** [comment]
> Try setting the compiler options to have ESNext (99) as the target

Sorry @orta, can you show me how I can do that?

**Comment by gr2m** [comment]
ugh I hate when I figure it out right after I ask the question. I swear I've tried to figure this out for a long time yesterday

But that's it, right?

```js
const sandboxConfig = {
  text: "",
  domID: "monaco-editor-embed",
  acquireTypes: false,
  compilerOptions: {
    target: "ESNext",
  },
};
```

**Comment by orta** [comment]
Yes, ( though I think it would take 99 )

I expected this repo to be a trivial example, but if you're using it to dive deep, I can add the types for sandbox etc in here?

**Comment by gr2m** [comment]
I'm no longer blocked by this issue, as I'm now exporting an async function. I store that code in IndexedDB, and then use ServiceWOrker to load it and return it at a virtual URL, such as `/sw/code.js`

Feel free to close if you like
