### ISSUE TITLE
JS + JSDoc mode?

### ISSUE THREAD

**Issue by gr2m** [orta/octokit-playground#5]
Is it be possible to use JavaScript instead of TypeScript for the code, but still receive all the TypeScript IntelliSense as in VS Code? Instead of setting types in code, would it be possible to use JSDoc?

I would like to do this:

```js
/**
 *  @param {import("@octokit/rest").Octokit} octokit
 */
export default async function (octokit) {
  const response = await octokit.request("GET /")
  return response.data
}
```

This would also workaround https://github.com/orta/octokit-playground/issues/4 for me

**Comment by orta** [comment]
Yep - the sandbox has a param for using JavaScript  - https://github.com/microsoft/TypeScript-website/blob/718277c81b6d5918cadcfa61ab06c1997e6afa2f/packages/sandbox/src/index.ts#L26

**Comment by orta** [comment]
https://github.com/orta/octokit-playground/pull/6 has types

**Comment by gr2m** [comment]
> Yep - the sandbox has a param for using JavaScript - https://github.com/microsoft/TypeScript-website/blob/718277c81b6d5918cadcfa61ab06c1997e6afa2f/packages/sandbox/src/index.ts#L26

Awesome, I just confirmed that it works!

I'm looking forward to show you what I'm working on!
